[settings]
timeout = 10000

# Build https://github.com/OmniBTC/polkadot/tree/release-v0.9.32-fix
[relaychain]
default_image = "comingweb3/polkadot:v0.9.32"
default_command = "polkadot"
default_args = [ "-lparachain=debug" ]
chain = "rococo-local"

[[relaychain.nodes]]
name = "alice"
ws_port = 9944

[[relaychain.nodes]]
name = "bob"

[[parachains]]
id = 2053
cumulus_based = true
chain = "dev"

[parachains.collator]
image = "comingweb3/psc:latest"
name = "psc01"
command = "psc"
args = [ "-lxcm=trace,evm=trace", "--pruning=archive" ]
ws_port = 9977
rpc_port = 8546