[settings]
timeout = 10000

# Build https://github.com/OmniBTC/polkadot/tree/release-v0.9.32-fix
[relaychain]
chain = "rococo-local"

[[relaychain.nodes]]
name = "alice"

[[relaychain.nodes]]
name = "bob"

[[parachains]]
id = 2053
cumulus_based = true

[parachains.collator]
name = "psc01"
command = "psc"
args = [ "-lxcm=trace" ]
